name: Deploy React Frontend (Vite)

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Clean old frontend files on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
             cd /home/ubuntu/bblpoker
             rm -rf frontend

      - name: Copy dist directory to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist"
          target: "/home/ubuntu/bblpoker/"

      - name: Rename dist to frontend on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mv /home/ubuntu/bblpoker/dist /home/ubuntu/bblpoker/frontend
            cd /home/ubuntu/bblpoker
            sudo docker compose down nginx
            sudo docker compose down backend
            sudo docker compose up -d nginx
